# Generated by Django 2.1.4 on 2018-12-08 16:33

import api.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mumin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('its_id', models.CharField(max_length=8)),
                ('jamaat_id', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(message="Jamaat ID must be entered in the format: 'A000'.", regex='^[A-Z]{1}\\d{3}$')])),
                ('hof_its_id', models.CharField(max_length=8)),
                ('is_hof', api.models.HofField(verbose_name='family head')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('province', models.CharField(max_length=2)),
                ('postal_code', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: 'A1A1A1'.", regex='^[A-Z][0-9][A-Z][0-9][A-Z][0-9]$')])),
                ('country', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('email_2', models.EmailField(blank=True, max_length=254)),
                ('cell_number', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '905-334-4583'.", regex='^\\d{3}-\\d{3}-\\d{4}$')])),
                ('res_number', models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '905-334-4583'.", regex='^\\d{3}-\\d{3}-\\d{4}$')])),
                ('other_number', models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '905-334-4583'.", regex='^\\d{3}-\\d{3}-\\d{4}$')])),
                ('zone', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Mumineen',
                'ordering': ['jamaat_id', 'its_id'],
            },
        ),
    ]
