# Generated by Django 2.1.4 on 2018-12-26 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mumin',
            name='title',
            field=models.CharField(blank=True, choices=[('Shaikh', 'Shaikh'), ('Mulla', 'Mulla'), ('Bhai', 'Bhai'), ('Bhen', 'Bhen')], max_length=10),
        ),
    ]
