# Generated by Django 2.1.4 on 2018-12-26 18:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_mumin_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='mumin',
            name='birthday',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mumin',
            name='relationship_to_hof',
            field=models.CharField(blank=True, choices=[('Self', 'Self'), ('Husband', 'Husband'), ('Wife', 'Wife'), ('Son', 'Son'), ('Daughter', 'Daughter'), ('Father', 'Father'), ('Mother', 'Mother'), ('Grand Father', 'Grand Father'), ('Grand Mother', 'Grand Mother'), ('Grand Daughter', 'Grand Daughter'), ('Grand Son', 'Grand Son'), ('Son-in-law', 'Son-in-law'), ('Daughter-in-law', 'Daughter-in-law'), ('Father-in-law', 'Father-in-law'), ('Mother-in-law', 'Mother-in-law'), ('Brother', 'Brother'), ('Sister', 'Sister'), ('Uncle', 'Uncle'), ('Aunt', 'Aunt'), ('Cousin', 'Cousin'), ('Niece', 'Niece'), ('Nephew', 'Nephew')], max_length=30, verbose_name='Relation to Head of Family'),
        ),
        migrations.AlterField(
            model_name='mumin',
            name='cell_number',
            field=models.CharField(help_text="Phone number must be entered in the format: '905-334-4583", max_length=12, validators=[django.core.validators.RegexValidator(message="Phone number not entered in the format: '905-334-4583'.", regex='^\\d{3}-\\d{3}-\\d{4}$')]),
        ),
        migrations.AlterField(
            model_name='mumin',
            name='jamaat_id',
            field=models.CharField(help_text="Jamaat ID must be entered in the format: 'A000'.", max_length=4, validators=[django.core.validators.RegexValidator(message="Jamaat ID not entered in the format: 'A000'.", regex='^[A-Z]{1}\\d{3}$')]),
        ),
        migrations.AlterField(
            model_name='mumin',
            name='other_number',
            field=models.CharField(blank=True, help_text="Phone number must be entered in the format: '905-334-4583", max_length=12, validators=[django.core.validators.RegexValidator(message="Phone number not entered in the format: '905-334-4583'.", regex='^\\d{3}-\\d{3}-\\d{4}$')]),
        ),
        migrations.AlterField(
            model_name='mumin',
            name='postal_code',
            field=models.CharField(help_text="Postal Code must be entered in the format: 'A1A1A1'.", max_length=6, validators=[django.core.validators.RegexValidator(message="Postal Code not entered in the format: 'A1A1A1'.", regex='^[A-Z][0-9][A-Z][0-9][A-Z][0-9]$')]),
        ),
        migrations.AlterField(
            model_name='mumin',
            name='res_number',
            field=models.CharField(blank=True, help_text="Phone number must be entered in the format: '905-334-4583", max_length=12, validators=[django.core.validators.RegexValidator(message="Phone number not entered in the format: '905-334-4583'.", regex='^\\d{3}-\\d{3}-\\d{4}$')]),
        ),
    ]
